server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: 100MB
      maxRequestSize: 150MB
  devtools:
    restart:
      enabled: true
  application:
    name: document-management-system
  jpa:
    datasource:
      initionalization-mode: always
      initialize: true
      schema: classpath:/data.sql
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true
    show-sql: true
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
